version: 1
name: aws-k8s
description: "AWS and Kubernetes CLI tooling"

steps:
  - name: AWS CLI
    type: brew
    formula: awscli

  - name: aws-iam-authenticator
    type: brew
    formula: aws-iam-authenticator

  - name: kubectl
    type: brew
    formula: kubernetes-cli
